const adminController = require("../controllers/adminController")
const express = require("express")
const Router = express.Router()

Router.get("/users",adminController.Users)
Router.get('/users/:id',adminController.userId)
Router.put('/useredit/:id',adminController.userEdit)
Router.delete('/userdelete/:id',adminController.userDelete)
Router.post("/groom",adminController.createGroom)
Router.get("/getgroom",adminController.getGroom)
Router.get('/getgroom/:id',adminController.getGroomId)
Router.put('/updategroom/:id',adminController.updateGroom)
Router.delete('/deletegrooming/:id',adminController.deleteGroom)
Router.post("/wellness",adminController.createWellness)
Router.get("/getwellness",adminController.getwellness)
Router.get('/getwellness/:id',adminController.getWellnessById)
Router.put('/updatewellness/:id',adminController.updatewellness)
Router.delete('/deletewellness/:id',adminController.deletewellness)
Router.post("/additional",adminController.createAdditional)
Router.get("/getadditional",adminController.getadditional)
Router.get('/getadditional/:id',adminController.getadditionalById)
Router.put('/updateadditional/:id',adminController.updateadditional)
Router.delete('/deleteadditional/:id',adminController.deleteadditional)
Router.post("/products",adminController.createProduct)
Router.get("/getproducts",adminController.getProduct)
Router.get('/getproduct/:id',adminController.getProductById)
Router.put('/updateproduct/:id',adminController.updateProduct)
Router.delete('/deleteproducts/:id',adminController.deleteProduct)

module.exports = Router